# docker-compose.yaml
# attempting with total available limits: 2.5GB RAM, 1 CPU
# I will tweak then so much in next commits
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - shared-temp:/app/temp
    env_file:
      - .env
    mem_limit: 512M
    cpus: 0.25

  worker:
    build: .
    command:
      [
        "/app/.venv/bin/celery",
        "-A", "server.celery_worker",
        "worker",
        "--loglevel=info",
        "--concurrency=1",
        "--max-tasks-per-child=1"
      ]
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
    volumes:
      - shared-temp:/app/temp
    env_file:
      - .env
    oom_kill_disable: false
    mem_limit: 2g
    cpus: 0.5

  redis:
    image: redis:8.0.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 5
    mem_limit: 512M
    cpus: 0.25

# shared volume to the API get access to files generated by the worker
volumes:
  shared-temp: