/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
  alias(libs.plugins.kotlinJvm)
  alias(libs.plugins.kotlinxSerialization)
  alias(libs.plugins.compose)
  alias(libs.plugins.composeCompiler)
  application
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
  maven { url = uri("https://plugins.gradle.org/m2/") }
  google()
  maven { url = uri("https://jitpack.io") }
}

dependencies {
  implementation(compose.desktop.currentOs)
  implementation(libs.flBase)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

application {
  // Define the main class for the application.
  mainClass = "com.lucasalfare.flbt.client.desktop.MainKt"
}

tasks.named<Test>("test") {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}
